---
title: "perf"
output: html_document
date: "2024-07-28"
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
```

## データの読み込み

```{r}
f <- function(filename) {
    read_csv(filename, col_names = c("value", "unit", "title")) %>%
    select(value, title) %>%
    mutate(value = value %>% str_replace("<not supported>", "NA") %>% as.numeric()) %>%
    mutate(title = title %>% str_replace_all("-", "_")) %>%
    pivot_wider(names_from = "title", values_from = "value") %>%
    mutate(filename = filename, board = basename(filename) %>% str_replace("perf_", "") %>% str_replace("\\.csv", ""))
}

d <- f("perf_raspi4.csv") %>% mutate(iterations = 110000) %>% union_all(f("perf_raspi5.csv") %>% mutate(iterations = 300000))
d$board <- d$board %>% as_factor
```

## データの書き出し

```{r}
d %>%
  write_tsv("perf.tsv")
```


## IPCの比較

```{r}
d %>%
  ggplot(mapping = aes(x = board, y = instructions / cycles)) +
  theme_bw() +
  geom_bar(stat = "identity") +
  scale_y_continuous(
    limits = c(0, 3),
    breaks = c(0, 1, 2, 3),
    minor_breaks = 0:30 / 5
  ) +
  geom_text(mapping = aes(
    y = instructions / cycles + 0.2,
    label = sprintf("%.2f", instructions / cycles)
  ))
```

## 分岐予測関係

### MPKI

```{r}
d %>%
  ggplot(mapping = aes(x = board, y = branch_misses / instructions * 1000)) +
  theme_bw() +
  geom_bar(stat = "identity") +
  scale_y_continuous(
    # limits = c(0, 3),
    # breaks = c(0, 1, 2, 3),
    # minor_breaks = 0:30 / 5
  ) +
  geom_text(mapping = aes(
    y = branch_misses / instructions * 1000 + 0.2,
    label = sprintf("%.1f", branch_misses / instructions * 1000)
  ))
```

### 分岐予測ヒット率


```{r}
d %>%
  ggplot(mapping = aes(x = board, y = 100 - branch_misses / branches * 100)) +
  theme_bw() +
  geom_bar(stat = "identity") +
  scale_y_continuous(
    # limits = c(0, 3),
    # breaks = c(0, 1, 2, 3),
    # minor_breaks = 0:30 / 5
  ) +
  geom_text(mapping = aes(
    y = 100 - branch_misses / branches * 100 + 2,
    label = sprintf("%.2f", 100 - branch_misses / branches * 100)
  ))
```


